"""End to end on real footage generated by ffmpeg. Skipped when ffmpeg is absent."""
import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from plantfloor.prepare import PrepOptions, prepare
from plantfloor.video.ffmpeg import probe_duration

HAVE_FFMPEG = bool(shutil.which("ffmpeg") and shutil.which("ffprobe"))


def make_clip(path: Path, lavfi: str) -> None:
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", lavfi, "-pix_fmt", "yuv420p", str(path)],
                   check=True)


@unittest.skipUnless(HAVE_FFMPEG, "ffmpeg not installed")
class PrepareEndToEnd(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        cls.raw = Path(cls.tmp.name, "raw"); cls.raw.mkdir()
        make_clip(cls.raw / "01_quiet.mp4", "color=c=gray:s=160x90:r=10:d=20")   # empty room
        make_clip(cls.raw / "02_busy.mp4", "testsrc2=s=160x90:r=10:d=12")        # motion
        cls.out = Path(cls.tmp.name, "chunks")
        opts = PrepOptions(chunk_len=5, sample_period=1, threshold=1.2, pad=1, min_gap=3, fps=2, width=160)
        cls.manifest = prepare(cls.raw, "2026-09-01 06:00", cls.out, opts, log=lambda _: None)

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def test_manifest_describes_both_files(self):
        m = json.loads((self.out / "manifest.json").read_text())
        self.assertEqual([s["name"] for s in m["sources"]], ["01_quiet.mp4", "02_busy.mp4"])
        self.assertAlmostEqual(m["total_seconds"], 32, delta=0.5)

    def test_dead_air_is_dropped(self):
        self.assertTrue(self.manifest["chunks"])
        self.assertTrue(all(c["source"] == "02_busy.mp4" for c in self.manifest["chunks"]))
        self.assertLess(self.manifest["kept_seconds"], self.manifest["total_seconds"] * 0.6)

    def test_every_clip_is_exported_with_its_planned_length(self):
        for c in self.manifest["chunks"]:
            clip = self.out / c["file"]
            self.assertTrue(clip.exists(), c["file"])
            self.assertAlmostEqual(probe_duration(clip), c["duration"], delta=0.6, msg=c["file"])


if __name__ == "__main__":
    unittest.main()
